### ISSUE TITLE
초급 019) 내용과 출력결과가 다릅니다.

### ISSUE THREAD

**Issue by shovel93** [js-200/js-200-examples#2]
설명하신 내용과 출력결과가 다릅니다.

변수명을 다르게 해야할것같습니다.

**Comment by shwldus3** [comment]
@shovel93 
결과값과 설명하는 내용에 차이가 있어 혼동을 드리게 된 점 죄송합니다.

넵 맞습니다.
학습하실 때에는 아래와 같이 코드를 실행하고 결과값을 확인해주세요
```
1 var value1 = null;
2 console.log(value1);
3 console.log(typeof value1);
4 var value2;
5 console.log(value2);
6 console.log(typeof value2);
```
설명내용에 적힌대로 5, 6문장의 결과는 undefined, undefined 입니다.

교정 작업중에 분리됐던 1-3문장과 4-6문장 예제를 하나로 합치는 수정작업 중에 발생한 오류였습니다..
다음 개정판에서 얘기주신 부분 꼭 수정반영 하도록 하겠습니다.

혹시 또 궁금한 점이 있다면 자유롭게 이슈로 문의주세요!
감사합니다

**Comment by shovel93** [comment]
넵 감사합니다!
