### ISSUE TITLE
중급 062) NaN 값 확인하기

### ISSUE THREAD

**Issue by shovel93** [js-200/js-200-examples#3]
중급 챕터 62에서, 
062-1.js 예제에 

```js
function verifyNumber(n) {
  if(!n || Number.isNaN(n)) return 0;
  return n;
}
```
이란 부분이 있는데요.

만약 `n`이 `NaN`값이면 `if`문의 조건 `!n`이 참이 되어서, 
`Number.isNaN(n)` 은 사실상 실행되지 않을 것 같습니다.

혹시 제가 잘못 이해하고 있는 부분이 있다면 알려주세요

**Comment by shwldus3** [comment]
@shovel93 안녕하세요 shovel93님 
네 정확합니다! 
예제 코드에서 !n 조건으로 NaN 이 미리 걸러져, Number.isNaN(n) 은 실행될 여지가 없습니다.

변명 아닌 변명을 드리자면
일반적으로 자바스크립트에서 verify 함수를 작성할 때 함수 첫 라인에서 if 문의 "!값" 형태의 코드를 자주 사용합니다.
예제문에서 다양한 verify 방식을 보여드리고자 추가로 추가로 작성하다보니 실수가 생긴 것 같습니다..

Number.isNaN 의 활용을 좀 더 잘 나타내기 위해서는
`
if(Number.isNaN(n) || !n) return 0;
`
이 더욱 적합한 코드였을 것 같아요
다음번 개정판에서 이부분 수정하여 더 적절한 예제로 거듭나도록 하겠습니다! 혼란을 드려 죄송합니다. 

다양하게 예제 실습해주시고 더 많이 질문주세요!
감사합니다

**Comment by shovel93** [comment]
@shwldus3 답변감사합니다!!
