### ISSUE TITLE
중급 068, 중급 069) 문자열 자르기 

### ISSUE THREAD

**Issue by shovel93** [js-200/js-200-examples#5]
중급 068에 7번 라인 설명부분 오타인가요?
```
첫 번째 인자보다 두 번째 인자가 크면 slice 함수는 정상적으로 수행되지 않습니다.
```

에서 첫 번째 인자가 더 크면, 혹은 더 오른쪽 인덱스? 이면 수행되지 않는 내용으로 되어야할거같습니다.

확인부탁드립니다.

중급 069 에도 비슷한 문장이 있습니다.

**Comment by jeado** [comment]
@shwldus3

**Comment by shwldus3** [comment]
안녕하세요 @shovel93 또 뵙네요! 학습 속도가 정말 빠르신 것 같아요..

넵 오타가 맞습니다. 
예제 코드에서 보신것처럼 slice(7, 2) 앞의 인자가 더 큽니다. 
첫번째 인자가 두번째 인자보다 크면 slice, substring 함수는 정상적으로 수행되지 않습니다.

부족한 부분인데 얘기주셔서 감사합니다
궁금한 부분이 생기면 또 질문해주세요!

**Comment by shovel93** [comment]
@shwldus3 코멘트감사합니다!

이슈 클로징할게요오옹
