### ISSUE TITLE
화살표 함수 이해하기 소스 코드 중에 문제가 있는 게 있습니다.

### ISSUE THREAD

**Issue by ghost** [js-200/js-200-examples#9]
`const printArguments = () => { console.log(arguments); } printArguments(1, 2, 3);`를 실행할 경우 책의 내용과 다른 결과가 출력됩니다. 이거 어떻게 해야지 책의 결과처럼 출력을 할 수 있나요?

**Comment by jeado** [comment]
크롬브라우저에서 확인하셨나요?

**Comment by ghost** [comment]
비주얼 스튜디오 코드에서만 확인을 했습니다.

**Comment by shwldus3** [comment]
@wwwcom1234

본문 중에서 실행된 [결과] 부분을 보면 
"위 코드를 크롬 콘솔에서 확인하면 다음과 같습니다" 내용이 있어요.

입문 003, 004 에서 얘기드린 것처럼 실행환경은 내용에 따라 두가지 방법으로 나뉩니다.
1. 비주얼 스튜디오 코드 Code Runner
2. 크롬 콘솔 실행환경
조금 헷갈리실 수도 있지만, 환경에 맞춰서 실행 부탁드립니다 ^^;

궁금한게 있으면 질문주세요. 감사합니다!
